bases:
-  ../../base

namespace: argocd

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#  - name: repo-github
#    envs: 
#      - github.env
#    type: Opaque
#
patchesStrategicMerge:
  - example-argocd-cr.yaml
  - argocd-admin-group.yaml
