bases:
-  ../../base

namespace: argocd

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: repo-github
  envs: 
  - github.env
  type: Opaque

patchesStrategicMerge:
  - patch-example-argocd-cr.yaml
  - patch-argo-admins.yaml
  - argocd-project.yaml
