apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      some: label
  accessModes:
    - ReadWriteMany
