apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  selector: 
    matchLabels:
      registry: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi 
