apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp-registry
  labels:
    registry: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /ocp-registry
    server: nasbook.foo.bar
  persistentVolumeReclaimPolicy: Retain 
