bases:
- ../../../monitoring
patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: APIServer
      name: cluster
    path: namedCert.yaml
  - target:
      group: config.openshift.io
      version: v1
      kind: APIServer
      name: cluster
    path: servingCert.yaml
  - target:
      group: operator.openshift.io
      version: v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    path: ingress-default-cert.yaml
  - target:
      group: operator.openshift.io
      version: v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    path: ingress-replicas.yaml
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: image-registry-storage
      namespace: openshift-image-registry
    path: registry-pvc.yaml
  - target:
      version: v1
      kind: PersistentVolume
      name: ocp-registry
    path: registry-pv.yaml
  - target:
      group: imageregistry.operator.openshift.io
      version: v1
      kind: Config
      name: cluster
    path: registry-cr.yaml
