apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  server:
    host: argocd.apps.hub.foo.bar
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, argo-admins, role:admin
    scopes: '[groups]'
  initialRepositories: |
    - url: https://github.com/hornjason/argocd-lab.git
      passwordSecret:
        name: repo-github
        key: password
      usernameSecret:
        name: repo-github
        key: username

