apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  managementState: Managed
  tolerations:
  - key: node-function
    operator: Exists
    effect: NoSchedule
  nodeSelector:
      node-role.kubernetes.io/infra: "" 
