apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kube-sealer
  namespace: kube-system
spec:
  channel: alpha
  name: sealed-secrets-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace 
