apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAeo7xJEKc4PO6OYgYd5pQbf4ENbZqEnrPWcGtwYbhj7RmRSAoPC4pz1FzbZQ1/8tTUcL0M3KXcEIKYz7xP3uBM8kq3LYSOTnniazCKAk6iPIPz0Pb92r89P1i35I83FWO/NWj75WgN4T/xC3d4dKuWBox3MaT8paAvmXJmzLK/NGEkQ81u5fC8jE8r5DppEMzoGg6POm4ws5b40jG/SzIAitk8VZjCVjd3vdGAp+PF6h7RiRwrpkpW4CNZbeStQgJDpTKrBoeFyMFlxyEaskfP0ViK2v8z2XVJ47cutMG1om6mMlhyi74wqCsQhQYCORqazjRZuLHjbvimDaB+Uasmv/uW3Y/TgnrTH99BGPK9GAO+MTh2zpG5YyoK9zSyKoILsHStUsybTpPxKZHSvRZzuJ8K0kWNYQvcLHhPJu/ToADgY3K5zE4hwcPsD7Z0srnLBrmH0nV+cJMATVvuFEcXk+f50nW+UR94KsHoF/pWHoAwkxBfJiWPrP4hLqgAlefQcz0+vdjsYSOelpCd21qyUb3qpr+/QstMx4FjXBQmko93BDQoFPTMQMsSVEk62qwuoCim64m93y3Kxx9uXuwgYOrQhW3ZP39XcyuBynnc/0iVsbvB5ZO2lBeQ++cRKErseOZjh+Cn+exdLbCS1pYLmMXtw4cILJXaSMEslC/DXirv9CH4FzM8GP3RSoLpkOIOzm7BrHpM1+kJZXJdqE/HW+zMvEHX/4k=
  template:
    metadata:
      creationTimestamp: null
      name: google-secret
      namespace: openshift-config
    type: Opaque

