apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: argocd
type: Opaque
data:
  alertmanager.yaml: AgDAtwxGF/DvlBAm/ICGBHqhxmbuv++ZjAw0kOCJ/5x26bZt02pk0dL/reABHNzZN3JVoCIwYXmlAECjVTOiSBNi3QfCyLTPg6ufu3cC+jMNBk7C/VXn/T6V0ncKYAtYlBjIBy2qUZKaWaFevHphj8+Z0qCD9pLbbEfAmTpjlIW2uQ+W2jo4g7I7bIKlgwp7mq678KUu8ct29mtIPNvobmj7fgmm+4i1cNd7LlT+jiQeksqgsVNlhPIag8MnZcRbXYLie4PvyLn8UPi+brRNwnOcFDVtTYJeMGdf1gwvKZ7/PtalCLOYoxnP6InSgjtnWAzLq25IN+oBOjo0QU8eHMbu4bdWEVVsA/4R8thxowO2RuKC1yzzgoM75fbIJmc0gbPuULQQYP+5IXvJm6D60CMiDqbL6Glliu674QNPWNKNNfybMQScgONkY/RqJ0ZFm664CImyz/mM+B5+bwVSRkVNH1mG+HhPVTm6acU+nafOqJUhYtMCUe6ZBXZwOo3OpQyZj8L1ego456wF9O8lf5Dv0FpNwO1MT+VmWBFwHFiD+J5rsvwJ7K0t0o7T+Gq+inM/qmfGMH4MF+ZL6djrZWFpsis8b+1Bx5AqWkc/F0hJG2k5P9t6iq+ZUSL6IvnMK+OqgaMlErXSa6J0BsRymX4IXiM8BE5N64+wcO9cfhPtcYDE8V9XkWTpTwHEdevCOzw=

