apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: argocd
type: Opaque
data:
  alertmanager.yaml: |
global:
  resolve_timeout: 5m
  slack_api_url: >-
    https://hooks.slack.com/services/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
receivers:
  - name: 'null'
    slack_configs:
      - channel: '#alerts'
  - name: slack-warn
    slack_configs:
      - channel: '#alerts'
route:
  group_by:
    - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: 'null'
  repeat_interval: 12h
  routes:
    - receiver: 'null'
      match:
        alertname: Watchdog
    - receiver: slack-warn
      match_re:
        severity: warning|critical
