apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  managementState: Managed
  logging: 2
  replicas: 2
  nodeSelector:
      node-role.kubernetes.io/infra: "" 
