apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  -  ../../../bases/bootstrap/argocd

secretGenerator:
  - name: repo-github
    envs: 
    - github.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
