apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-kubelet
spec:
  machineConfigPoolSelector:
    matchLabels:
      customkubelet: 'True'
  kubeletConfig:
    evictionHard: 
      memory.available: "5%"
      nodefs.available: "5%"
      nodefs.inodesFree: "5%"
      imagefs.available: "5%"
      imagefs.inodesFree: "5%"
    evictionMaxPodGracePeriod: 10
    evictionSoft:
      memory.available: "10%"
      nodefs.available: "10%"
      nodefs.inodesFree: "10%"
      imagefs.available: "10%"
      imagefs.inodesFree: "10%"
    evictionSoftGracePeriod:
      memory.available: "2m"
      nodefs.available: "2m"
      nodefs.inodesFree: "2m"
      imagefs.available: "2m"
      imagefs.inodesFree: "2m"
#   featureGates: 
#     RotateKubeletClientCertificate: True
#     RotateKubeletServerCertificate: True
    kubeReserved: 
      cpu: "0.5m"
      memory: "3Gi"
    systemReserved: 
      cpu: "0.5m"
      memory: "3Gi"
