apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
spec:
  nodePlacement:
    tolerations:
      - key: node-function
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: "" 
