apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identityprovider
spec:
  destination:
    namespace: identity
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
  source:
    path: overlays/lab/identity
    repoURL: "https://github.com/hornjason/argocd-lab.git"
    targetRevision: master
