apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAY44UkqhOyIXF1KpvYl9lfX8nT7u34sahhXP33rHVKY+i04Gw1Kltf3/vxm+FHHS718V+sa/Q7UxUGS1zvCriZzxInjpc57PPqAr96VolLBCB8XhgrdtSTGsOwp6TQ/sJ5ZLPbF2ACDpy7PHJ2vKo0kBMT4PCo30HgwLhyIvVDwLB0+WDtsfMW2R/WaQ3kFXMakE5tZKueiGJqWOTsx1sG/nvskvMWw4Eh3ggJzx+P0oWXeYaJc1LMRu24h0ZBQ7050a3Ihn7Dq9x0jfz0/PyQfGiHCYG2ujnSw8OZA8WLrGE7b11dkWx0jX44sQZJmrlLwJu9LD7dEhJ2m7SD9GYj16DI6AA9a0Th8bb4/69EvtllREx77NPznHz8g8QnK0B++FUoCjx7xMH/lEnWY15hX5IQGmb6mkUW1Jrx08nJnfWBiTP6F3tQqbUTxkwhrGK9ruSdnIGLTtnL9tLHfgeONeQ/gPX3FJP+eilnEV8T+PSPVpvc0Zf2mng06Zx5s94aLQn5Ugl3B2mX29cMKR/2gLdomxq4M2MT7R6+qSLg0pI/rnsesxXNdq/EB7la5KfRDRVen2VGDywlMGTm4YemndIBOZQkn7LIZiDDqBdrElrYObNTEYqc92Ep/g8ICVfl5QTrF0NlAS11eKFN9DyIwhYr6YU3JAjxGPaQvBVhV758HJjwyyPJvRQyiXyOxxS03M53EPU+ZnneBA009E0OdBP6O4VcZIU=
  template:
    metadata:
      creationTimestamp: null
      name: google-secret
      namespace: openshift-config
    type: Opaque

