apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgChr8Xdqi9ZF9aStZ02YrG7Bj7zLWNuKxu/ouQWorkHpnAXuvJqTMCrWJ1h32kd4g/WeI8IKnF47O3QNppMgM/YscVg8/l6pV+zdfpZw9rK8cNefWRYHPLxt687FnHj8lCzpguB/yDd1S9PMdXBHh9BfhZJCfbqiwEa7FIcJW/qxnBPANN9xfQU0aUN5pxCK9Az7RCJlkAC25NmH8w+AStmuu0QxOA47Q/7Cs6NiL6uWXaUF+bL3j+UiMbgMajBP+tWLl/PFhSVZYTDliIKdrMNwiumFNZqZEyXsbXG06wdkNHtTuLpZ7oSKqOWXZG1A3pw/HM//Itf2hKOE9lJxsg6bb2o1iR4Lafq9RgjEzBnWabsGUUcJzgMr60xbYfIzScQYbKJTZEbUJucQFA0/b3EqnAKRhCMkc3zqhx9J+lqsQBR/NLjwum9B2r1Tygfi7A2JhUaAAQNTzTl2aXns78MP4+jkbjnewm7Gg3aB3TTeI0OPddQdToDKod5VhwY4iwibSVSLeuXRW/4sDzW5kpp6UDwNuQyVJXoXjZQ0LEKHrlYDeFiP3lm51zy7TwxtM2Ew/05dzB+4m6i7bbjqxNhAO6/23JnpsDoIDQXLz0VpsrS7lVNTrc3flVL7Qd9Xk6bnk5WDaftWvzUTuv7VI5OhAo+/C+fR5LPaFHbsgBRDq8tL7sI8aEklDoCgthTwXU4ut09r7FzSbQ+YKmY5HT7cAWxoyTN3EM=
  template:
    metadata:
      creationTimestamp: null
      name: google-secret
      namespace: openshift-config
    type: Opaque

